version: '3.9'

services:
  app:
    build: .
    container_name: node-app
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: mysql://root:1234@host.docker.internal:3306/greenpark
    volumes:
      - .:/app
    command: sh -c "npx prisma migrate deploy && node dist/main.js"
